### ISSUE TITLE
if tutorials are originally in markdown, they don't get converted

### ISSUE THREAD

**Issue by gkatsev** [nhnent/tui.jsdoc-template#12]
When using this template, if the tutorials are in markdown, they just get copied to the destination directory's `tutorials/` folder without conversion.

Also, if tutorials aren't configured as a config option, this template will fail because there's no null check here https://github.com/nhnent/tui.jsdoc-template/blob/master/publish.js#L718.

I'll probably look into this tomorrow, but wanted to post an issue about it first.

**Comment by gkatsev** [comment]
This isn't as much of a problem when deployed on github pages now because it'll auto-render markdown now, but means that it looks a bit different than everything else.

**Comment by minkyu-yi** [comment]
I missed this problem.
Could you PR to fix it?

Thanks.

**Comment by gkatsev** [comment]
I have a fix for the null check.
Still trying to figure out the best way of rendering out the markdown so it looks like other pages, for example, similar to the README.

**Comment by gkatsev** [comment]
@minkyu-yi For rendering out the markdown tutorials, what about updating the [article](https://github.com/nhnent/tui.jsdoc-template/blob/master/tmpl/tutorial.tmpl#L30-L37) in the tutorial.tmpl to either output an iframe for the html page or render out the markdown inline? Then, the styles are easily available for the markdown without any extra work.

**Comment by minkyu-yi** [comment]
@gkatsev Fixed in PR #13.
See the PR with demo.

Could you feedback to me? 😊

**Comment by gkatsev** [comment]
Sweet! Yeah, I'll take a look in the next couple of days.

**Comment by gkatsev** [comment]
Solved via #13 and #14.
