### ISSUE TITLE
Customize styles

### ISSUE THREAD

**Issue by gkatsev** [nhnent/tui.jsdoc-template#15]
Have you considered making the styles like background color of the footer etc customizable?

At first, I thought that making those be variables in the templates config might be useful but I'm now leaning towards providing a stylesheet field (or array) for urls that are included [after the built-in styles](https://github.com/nhnent/tui.jsdoc-template/blob/master/tmpl/layout.tmpl#L51).

And maybe also a scripts array but I think that isn't quite as necessary.

If you think it's a good idea, I can definitely make a PR for that.

**Comment by minkyu-yi** [comment]
Yeah, that's a good idea.
I think we can conjugate with [jsdoc's static files](http://usejsdoc.org/about-configuring-default-template.html#copying-static-files-to-the-output-directory).

```
templates: {
  defaults: {
    staticFiles: {
      include: [...]
      exclude: [...]  <-- Maybe we can exclude the built-in styles
    }
  },
  css(?): [...]  <-- new feature with staticFiles property
}
```

**Comment by gkatsev** [comment]
I made a PR for an initial solution: #17.

**Comment by minkyu-yi** [comment]
v1.1.0 published to npm.js

Thank you :)
