### ISSUE TITLE
Hide »API / Examples(Tutorials)« navigation if there are no tutorials

### ISSUE THREAD

**Issue by mischah** [nhnent/tui.jsdoc-template#2]
Hej,

this JSDoc template really looks promising 💖 

But I wonder if its possible to hide the navigation to switch between API and examples if a project comes without examples.

I would think that it should be hidden automatically if there is no `tutorials` property in the JSDoc configuration.

**Comment by mischah** [comment]
Would you accepts a pull request for that?

**Comment by minkyu-yi** [comment]
Released 1.0.4

**Comment by mischah** [comment]
👌
