### ISSUE TITLE
timeline for 1.1.0 and thanks

### ISSUE THREAD

**Issue by gkatsev** [nhnent/tui.jsdoc-template#22]
Hi,

Just wanted to say thanks for the template and for being so responsive. Wanted to add that we're going to be using it for the docs on the new [videojs](videojs.com) docs website (will be at http://docs.videojs.com when it launches).

Was wondering what the timeline for a 1.1.0 release would be. Having the version switcher would be cool to  have. Also, wanted to offer any help you'd need in getting that release out.

Thanks and keep up the great work! 🎉

**Comment by gkatsev** [comment]
Also, let me know if you want me to rebase my PRs against the `develop` branch instead of master.

**Comment by minkyu-yi** [comment]
Yeah~, Thank you.
I expect 1.1.0 will be released next week.

And yes,  I would appreciate it if PRs are based on develop. 😃

**Comment by gkatsev** [comment]
All my PRs are now rebased against develop.

**Comment by minkyu-yi** [comment]
v1.1.0 published to npm.js

Thank you :)
