### ISSUE TITLE
Add an option to make the logo linkable

### ISSUE THREAD

**Issue by gkatsev** [nhnent/tui.jsdoc-template#25]
Any thoughts to making the logo linkable if the logo options contain a `link` property?

For example, as we're using it for video.js, the docs will live on another subdomain, and would be nice to have the logo either re-direct to `videojs.com` or maybe back to the docs home.

**Comment by minkyu-yi** [comment]
Yeah, I agree.

I think the below spec reasonable. How about you?

```
"templates": {
    "logo": {
        "url": "http://nhnent.github.io/tui.component.tree/latest/styles/logo.png",
        "width": "150px",
        "height": "13px"
        "link": "https://github.com/nhnent/tui.jsdoc-template/"
    }
}
```

* Default: Repository url from `package.json`
* Rendering
  if (logo.url) {`<a> <img> </a>`}
  else {`<img>`}

**Comment by gkatsev** [comment]
Looks great.

**Comment by minkyu-yi** [comment]
Yeah, I registered this in 1.2.0 milestone.
Thanks 😄

**Comment by minkyu-yi** [comment]
Done.
v1.2.0
