### ISSUE TITLE
Problem on fs.copyFileSync when publishing files to destination directory with node v8.5.0

### ISSUE THREAD

**Issue by rcmsjr** [nhnent/tui.jsdoc-template#29]
Generating output files...
fs.js:1919
  binding.copyFile(src, dest, flags);
          ^

Error: EPERM: operation not permitted, copyfile 'C:\Users\roberto.souza\Projects\channel-manager\node_modules\tui-jsdoc-template\static\fonts\glyphicons-halflings-regular.eot' -> 'C:\Users\roberto.souza\Projects\channel-manager\server\docs\fonts'
    at Object.fs.copyFileSync (fs.js:1919:11)
    at C:\Users\roberto.souza\Projects\channel-manager\node_modules\tui-jsdoc-template\publish.js:612:12

This error occurs because when publishing the files to the destination directory, the fs.copyFileSync command is setting the destination to only directory, but in the node latest, you should indicate the full path with the filename in the destination parameter.

**Comment by ricardofadini** [comment]
+1

**Comment by roberto-souza-dbc** [comment]
+1

**Comment by hwguilherme** [comment]
+1

**Comment by minkyu-yi** [comment]
Use jsdoc ^3.5.5
