### ISSUE TITLE
Collapse shown sub nav items when clicking the most parent nav item

### ISSUE THREAD

**Issue by mischah** [nhnent/tui.jsdoc-template#3]
Hej, 

I would love to have the behavior that opened sub navigations can be collapsed when clicking the parent nav items. 

That would make it easier to explore the API.

See:
![collapse](https://cloud.githubusercontent.com/assets/441011/20194864/6d3ad52c-a794-11e6-9d46-34a9a0c9f7de.gif)

**Comment by mischah** [comment]
Would you accepts a pull request for that?

**Comment by minkyu-yi** [comment]
Why not?
I agree that is a good UX.
